apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.fedapayApiUrl }}
  FEDAPAY_API_URL: {{ .Values.secrets.fedapayApiUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.fedapayApiKey }}
  FEDAPAY_API_KEY: {{ .Values.secrets.fedapayApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.fedapayWebhookSecret }}
  FEDAPAY_WEBHOOK_SECRET: {{ .Values.secrets.fedapayWebhookSecret | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
