apiVersion: v2
name: file-service
description: A Helm chart for tissiMah File Service
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: tissi-mah Team
    email: kpeewu@gmail.com

keywords:
  - file
  - storage
  - s3
  - grpc
  - golang
  - microservice

home: https://github.com/Kpeewu/tissi-mah
sources:
  - https://github.com/Kpeewu/tissi-mah/tree/main/services/file-service
