apiVersion: v2
name: auth-service
description: A Helm chart for tissmah kong ingress controller
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: tissi-mah Team
    email: kpeewu@gmail.com

keywords:
  - grpc
  - jwt
  - cors

home: https://github.com/Kpeewu/tissi-mah
sources:
  - https://github.com/Kpeewu/tissi-mah/tree/main/services/auth-service
