apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyc-service.fullname" . }}
  labels:
    {{- include "kyc-service.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  GRPC_PORT: {{ .Values.service.port | quote }}
  FILE_SERVICE_HOST: {{ .Values.config.fileServiceHost | quote }}
  FILE_SERVICE_PORT: {{ .Values.config.fileServicePort | quote }}
  USER_SERVICE_HOST: {{ .Values.config.userServiceHost | quote }}
  USER_SERVICE_PORT: {{ .Values.config.userServicePort | quote }}
  SUPPORT_SERVICE_HOST: {{ .Values.config.supportServiceHost | quote }}
  SUPPORT_SERVICE_PORT: {{ .Values.config.supportServicePort | quote }}
  VEHICLE_SERVICE_HOST: {{ .Values.config.vehicleServiceHost | quote }}
  VEHICLE_SERVICE_PORT: {{ .Values.config.vehicleServicePort | quote }}
  {{- range $key, $value := .Values.config.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
