apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "push-service.fullname" . }}
  labels:
    {{- include "push-service.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  GRPC_PORT: {{ .Values.service.port | quote }}
  FIREBASE_CREDENTIALS_PATH: "/etc/push-service/firebase-credentials.json"
  {{- range $key, $value := .Values.config.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
