apiVersion: v1
kind: Secret
metadata:
  name: {{ include "push-service.fullname" . }}
  labels:
    {{- include "push-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.firebaseCredentials }}
  firebase-credentials.json: {{ .Values.secrets.firebaseCredentials | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
