apiVersion: v1
kind: Secret
metadata:
  name: {{ include "email-service.fullname" . }}
  labels:
    {{- include "email-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.sendgridApiKey }}
  SENDGRID_API_KEY: {{ .Values.secrets.sendgridApiKey | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
