apiVersion: v1
kind: Secret
metadata:
  name: {{ include "email-service.fullname" . }}
  labels:
    {{- include "email-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.smtpUsername }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
