apiVersion: v1
kind: Service
metadata:
  name: tileserver-gl
  namespace: default
  labels:
    app: tileserver-gl
    tier: tiles
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: tileserver-gl
