name: "Terraform Plan - Production"

on:
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/terraform/**"
      - ".github/workflows/terraform-plan-prod.yml"
  workflow_dispatch:

jobs:
  plan:
    name: "Terraform Plan (Production)"
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "TODO - Terraform plan production"
